name: Build Release
on:
  release:
    types: [created]
  workflow_dispatch: # 保留手动触发按钮

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: ['stable']
        os: [ubuntu-latest]
        arch: ['amd64'] # 只编译 x64
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      # 🎯 修复这里：换成官方的 setup-go，彻底解决报错
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Setup Env
        run: >-
          sudo apt-get update &&
          sudo apt-get install
          bc
          gcc
          libgl1-mesa-dev
          libwayland-dev
          libx11-dev
          libxkbcommon-dev
          xorg-dev
          xvfb
      - name: Setup fyne
        run: go install github.com/fyne-io/fyne-cross@latest
      - name: Install UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true
      - name: Package
        run: fyne-cross windows -arch=${{ matrix.arch }}
      - name: Compress
        run: |
            mkdir ${GITHUB_WORKSPACE}/dist
            unzip ${GITHUB_WORKSPACE}/fyne-cross/dist/windows-${{ matrix.arch }}/chrome_updater.exe.zip -d ${GITHUB_WORKSPACE}/fyne-cross/dist/windows-${{ matrix.arch }}
            mv -f ${GITHUB_WORKSPACE}/fyne-cross/dist/windows-${{ matrix.arch }}/chrome_updater.exe ${GITHUB_WORKSPACE}/dist/chrome_updater.exe
            
            # 直接进行 upx 压缩
            upx -9 ${GITHUB_WORKSPACE}/dist/chrome_updater.exe
            
            zip -rj ${GITHUB_WORKSPACE}/dist/chrome_updater-windows-${{ matrix.arch }}.zip ${GITHUB_WORKSPACE}/dist/chrome_updater.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/chrome_updater-windows-${{ matrix.arch }}.zip
